DB_USER = 'qmyz'
DB_PASSWORD = 'aZIKZOEpueizVg'
DB = 'qmyz'
DB_URL = 'localhost'
DB_PORT = 5432

CELERY_BROKER_URL = 'redis://:cAEsc02RXdUSaQiL@localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://:cAEsc02RXdUSaQiL@localhost:6379/0'

PASSWORD_HASH_FUNC_NAME = 'sha512'
PASSWORD_HASH_ITERATIONS = 10_0000
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7
SECRET_KEY = 'w8OJFC0lAYaRnRGbrANR_M16QAO6qIcZfLv--h5gKLM'
